sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t tanggun/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true tanggun/docker-react-app npm run test -- --coverage

after_success:
  - echo "test success!"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
  bucket_path: docker-react-app
  on:
    branch: main

  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_access_key
